apiVersion: apps/v1
kind: Deployment
metadata:
  name: homes-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homes
  template:
    metadata:
      labels:
        app: homes
    spec:
      containers:
        - name: homes
          image: dsprouts/homes
          env:
            - name: MONGO_URI
              value: 'mongodb://homes-mongo-srv:27017/homes'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: gethomes
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

---
# ClusterIP service config. It can be done on a stand alone config but since there's a 1-1 mapping between service and deployments. This works
apiVersion: v1
kind: Service
metadata:
  name: homes-srv
spec:
  selector:
    app: homes
  ports:
    - name: homes
      protocol: TCP
      port: 3000
      targetPort: 3000
